import type {TutorialGame} from './tutorials';
export type Example={prompt:string;subline:string;fields:[string,string][];cards?:number[];series?:number[];book?:[string,string];result:string;calculation:string;notes:[string,string,string];keys:string;timer:string};
export const guideExamples:Record<TutorialGame,Example>={
 arithmetic:{prompt:'8 × 25',subline:'Multiplication · first factor × second factor',fields:[['Your answer','200']],result:'Correct → next problem',calculation:'8 × 25 = 8 × 100 ÷ 4 = 200. One point is added immediately.',notes:['Read the operation first. The timer and running score stay above the prompt.','Type 200 in the answer box. A correct arithmetic answer advances immediately, without Enter.','Arithmetic has no separate review screen. Your next prompt replaces this one; results appear when the sprint ends.'],keys:'Type to answer · Enter checks · Escape skips',timer:'1:42'},
 'mental-math':{prompt:'80 → 100. Percentage change?',subline:'Enter a signed percentage.',fields:[['Your answer','25%']],result:'Correct · 25%',calculation:'(100 − 80) ÷ 80 × 100 = 25%. Divide by the starting value.',notes:['Identify the requested quantity and rounding rule before calculating.','Type 25 or 25%, then press Enter. Unlike Arithmetic, you submit the answer explicitly.','Read the explanation, then press Enter again. Review time still uses the session clock.'],keys:'Enter submits / continues · Escape skips',timer:'1:42'},
 dice:{prompt:'Public fair value 7.00',subline:'Two hidden dice · no modifier or event loss',fields:[['Your bid','6.00'],['Your ask','8.00']],result:'Counterparty sold → you bought 1 @ 6.00',calculation:'Cash −6, inventory +1. At a final payout of 8, gross profit is +2 before inventory and timeout charges.',notes:['Hidden fair dice average 3.5 each. Watch inventory as well as marked P&L.','Your bid is where you buy; your ask is where you sell. Enter moves bid → ask → submit. A fill is not guaranteed.','This sample fill adds one unit. Review pauses the timer. Inventory carries forward and incurs a quadratic charge each round.'],keys:'Enter: bid → ask → submit → next round',timer:'25s'},
 cards:{prompt:'Fair value ≈ 10.08',subline:'One visible 3 + one hidden card',cards:[3,0],book:['8.00','9.00'],fields:[],result:'Buy 1 at the ask: 9.00',calculation:'EV = 3 + (364 − 3)/51 ≈ 10.08. Buying at 9 captures about +1.08 expected edge.',notes:['Visible cards contribute to payout and are removed when valuing the hidden cards. Easy displays an EV hint.','The book bid is where you sell; the ask is where you buy. B buys, S sells, P passes.','Captured expected edge determines score. A bad realized draw can lose money even when buying was optimal.'],keys:'B buy · S sell · P pass · Enter next',timer:'24s'},
 fermi:{prompt:'Estimate the modeled town’s daily water use.',subline:'10 residents × 100 litres per resident',fields:[['Lower bound','800'],['Upper bound','1200']],result:'Hit · target 1,000 litres',calculation:'At halfway through a Medium timer: width = 400/1,000 = 0.4; points = 100 × (1/1.4) × 0.875 = 62.50.',notes:['Read units and assumptions. Multiply residents by use per person to build an estimate.','Enter positive bounds with low < high. Enter moves lower → upper → submit. Narrower successful ranges earn more.','A hit includes either boundary. Review separates coverage, precision and speed; a miss earns zero.'],keys:'Enter: low → high → submit → next',timer:'23s'},
 events:{prompt:'Will the next delivery arrive on time?',subline:'60 / 100 past on-time deliveries · simulated sample',fields:[['Probability forecast (%)','60'],['Your bid','55'],['Your ask','65']],result:'You bought at 55 · YES pays 100',calculation:'P&L +45. Brier = (0.6 − 1)² = 0.16. At weight 20, adjustment +1.80; combined score +46.80.',notes:['The sample rate is evidence, not the hidden true probability. The event pays 100 for YES and 0 for NO.','Forecast and quote are separate. Enter 60 for 60%. You buy at 55 or sell at 65 if traders choose to fill you.','This example shows one fill and a YES outcome. Noise traders and one informed trader may produce other fills; all settle before the next event.'],keys:'Enter: forecast → bid → ask → submit',timer:'28s'},
 trading:{prompt:'Fair value 100.00',subline:'Stage 1: quote · Stage 2: take a separate book',fields:[['Your bid','99.00'],['Your ask','101.00']],book:['102.00','103.00'],result:'Buy passively at 99, then sell actively at 102',calculation:'Positions offset. Combined gross P&L = 102 − 99 = +3, regardless of payout; timeout charges would be deducted.',notes:['Both stages trade the same contract. The separate book is hidden until after you post your quote.','First submit 99 / 101. If you buy at 99, review the fill, then open the separate book shown here. Sell at its bid of 102.','Both legs settle at the same payout. Reviews show passive and active P&L separately; inventory resets each round.'],keys:'Enter quotes / advances · B / S / P takes',timer:'20s'},
 ev:{prompt:'Pay 4; 25% chance to receive 20, otherwise 0.',subline:'Expected net profit per play?',fields:[['Your answer','1']],result:'Correct · expected net profit +1',calculation:'0.25 × 20 + 0.75 × 0 − 4 = 1. Receipts are gross, so subtract the fee once.',notes:['Read whether the question wants profit, a break-even entry price, a probability, or a yes/no decision.','For this money question enter 1. Probability questions also accept fractions and percentages; +EV decisions accept yes/no.','The explanation shows the calculation. Review time counts toward the sprint, so press Enter when ready.'],keys:'Enter submits / continues · Escape skips',timer:'1:42'},
 series:{prompt:'What comes next?',subline:'Growing differences · example',series:[3,6,10,15,21,28],fields:[['Next integer','36']],result:'Correct · 36',calculation:'Gaps are 3, 4, 5, 6, 7. Next gap is 8, so 28 + 8 = 36.',notes:['Inspect every term. Try differences, ratios, alternating positions or a recurrence.','Type the next integer, then Enter. The family name is hidden during play unless hints are enabled.','Review reveals the intended rule. Finite sequences can fit other rules; grading follows the generated family.'],keys:'Enter submits / continues · Escape skips',timer:'1:42'},
 'twenty-four':{prompt:'Make 24',subline:'Use each displayed value exactly once.',cards:[1,2,3,4],fields:[['Your expression','(1 + 3) * (2 + 4)']],result:'Correct · 24',calculation:'1 + 3 = 4 → 2 + 4 = 6 → 4 × 6 = 24. Other valid expressions are accepted too.',notes:['Look for factors of the target: 24 = 4 × 6. Suits are decorative; the four values are what matter.','Type an expression using all four cards. Parentheses control grouping. Use * or × to multiply and / or ÷ to divide.','Review lists evaluation steps and puts Next on its own row. Invalid syntax stays editable; a valid wrong result reveals a solution.'],keys:'Enter checks / continues · Escape skips',timer:'1:42'}
};
