import {variedGenerator} from '../../shared/variety.mjs';
import {useEffect,useRef,useState} from 'react';
import {defaults,problem,validConfig,editableArithmeticConfig} from '../../shared/model.mjs';
import type {Config,Difficulty,Preset,Session} from '../lib/types';
import ArithmeticRanges from '../components/ArithmeticRanges';
const nextVariedProblem=variedGenerator(problem,q=>`${q.a}:${q.symbol}:${q.b}`);
export default function Arithmetic({presets,onSave,onPreset,onBusy}:{presets:Preset<Config>[];onSave:(s:Session)=>Promise<void>;onPreset:(p:Preset<Config>)=>Promise<void>;onBusy:(v:boolean)=>void}){
 const [difficulty,setDifficulty]=useState<Difficulty>('Medium');const [config,setConfig]=useState<Config>(structuredClone(defaults.Medium));
 const [phase,setPhase]=useState<'setup'|'play'|'result'>('setup');const [q,setQ]=useState(()=>nextVariedProblem(config));const [answer,setAnswer]=useState('');
 const [remaining,setRemaining]=useState(config.duration);const [score,setScore]=useState(0);const [feedback,setFeedback]=useState('');const [name,setName]=useState('');const [error,setError]=useState('');const [saved,setSaved]=useState(false);const [saving,setSaving]=useState(false);const [result,setResult]=useState<Session|null>(null);
 const run=useRef({start:0,deadline:0,questionStart:0,correct:0,errors:0,times:[] as number[],active:false});const input=useRef<HTMLInputElement>(null);const lastWrong=useRef('');
 useEffect(()=>()=>{run.current.active=false;onBusy(false);},[onBusy]);
 async function persist(s:Session){setSaving(true);setError('');try{await onSave(s);setSaved(true);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 function finish(){if(!run.current.active)return;run.current.active=false;onBusy(false);const r=run.current;const duration=config.duration;const s:Session={id:crypto.randomUUID(),timestamp:new Date().toISOString(),game:'arithmetic',difficulty,score:r.correct,accuracy:r.correct/Math.max(1,r.correct+r.errors),avgResponseMs:r.times.length?r.times.reduce((a,b)=>a+b,0)/r.times.length:0,duration,correct:r.correct,errors:r.errors,config:structuredClone(config)};setResult(s);setPhase('result');void persist(s);}
 useEffect(()=>{if(phase!=='play')return;const tick=()=>{const left=Math.max(0,Math.ceil((run.current.deadline-performance.now())/1000));setRemaining(left);if(!left)finish();};const timer=setInterval(tick,100);return()=>clearInterval(timer);},[phase]);
 useEffect(()=>{if(phase!=='play')return;const prevent=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[phase]);
 function start(){if(!validConfig(config)){setError('Choose at least one operation, valid ranges (1–10,000), and 10–3,600 seconds. Division ranges must allow at least one whole-number answer.');return;}const now=performance.now();run.current={start:now,deadline:now+config.duration*1000,questionStart:now,correct:0,errors:0,times:[],active:true};setQ(nextVariedProblem(config));setAnswer('');setScore(0);setRemaining(config.duration);setFeedback('');setError('');setSaved(false);lastWrong.current='';setPhase('play');onBusy(true);}
 function next(){setQ(nextVariedProblem(config));setAnswer('');lastWrong.current='';run.current.questionStart=performance.now();input.current?.focus();}
 function change(v:string){if(!run.current.active)return;if(performance.now()>=run.current.deadline){finish();return;}setAnswer(v);if(v.trim()!==''&&Number(v)===q.answer){run.current.correct++;run.current.times.push(performance.now()-run.current.questionStart);setScore(run.current.correct);setFeedback('Correct');next();}}
 function check(){if(performance.now()>=run.current.deadline){finish();return;}if(answer.trim()&&answer!==lastWrong.current){run.current.errors++;lastWrong.current=answer;setFeedback('Try again');}}
 function skip(){if(performance.now()>=run.current.deadline){finish();return;}run.current.errors++;setFeedback(`Skipped · ${q.a} ${q.symbol} ${q.b} = ${q.answer}`);next();}
 function editConfig(c:Config){setConfig(c);setDifficulty('Custom');}
 if(phase==='play')return <main className="play"><div className="playbar"><span>ARITHMETIC SPRINT</span><span className={remaining<=10?'danger':''}>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')} <small>remaining</small></span><span>{score} <small>correct</small></span></div><div className="timertrack"><div style={{width:`${remaining/config.duration*100}%`}}/></div><div className="problem"><p className="eyebrow">{difficulty} · {config.duration}s</p><h1>{q.a} <span>{q.symbol}</span> {q.b}</h1><input ref={input} aria-label="Your answer" autoFocus autoComplete="off" inputMode="numeric" value={answer} onChange={e=>change(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();check();}if(e.key==='Escape'){e.preventDefault();skip();}}}/><p className="feedback" aria-live="polite">{feedback||'Find your rhythm.'}</p><p className="hint">Correct answers advance automatically<br/><kbd>enter</kbd> check · <kbd>esc</kbd> skip</p></div></main>;
 if(phase==='result'&&result)return <main className="result"><p className="eyebrow">SESSION COMPLETE</p><h1>A little sharper.</h1><div className="bigscore">{result.score}<span>correct answers</span></div><div className="metrics"><div><strong>{Math.round(result.accuracy*100)}%</strong><span>Accuracy</span></div><div><strong>{(result.avgResponseMs/1000).toFixed(2)}s</strong><span>Avg. correct response</span></div><div><strong>{result.errors}</strong><span>Checks missed + skips</span></div></div><p className="muted">{saving?'Saving session…':saved?'Session saved. Keep the momentum.':'Session not yet saved.'}</p>{error&&<p role="alert" className="danger">{error} <button disabled={saving} onClick={()=>persist(result)}>Retry save</button></p>}<button className="primary" disabled={!saved} onClick={start}>Practice again ↗</button> <button disabled={!saved} onClick={()=>setPhase('setup')}>Adjust settings</button><p><a href="#/history">View progress →</a></p></main>;
 return <main><div className="pageheading"><div><p className="eyebrow">01 / FOUNDATION</p><h1>Arithmetic sprint</h1><p className="muted">Small calculations. Faster instincts.</p></div><a className="textlink" href="#/">← All modes</a></div><div className="setupgrid"><section className="panel"><h2>Your session</h2><label className="fieldlabel">Difficulty</label><div className="segmented">{(['Easy','Medium','Hard','Custom'] as Difficulty[]).map(d=><button key={d} aria-pressed={difficulty===d} className={difficulty===d?'selected':''} onClick={()=>{setDifficulty(d);if(d!=='Custom')setConfig(structuredClone(defaults[d]));}}>{d}</button>)}</div><label className="duration">Duration <span><input aria-label="Duration in seconds" type="number" min="10" max="3600" value={config.duration} onChange={e=>editConfig({...config,duration:Number(e.target.value)})}/> seconds</span></label><ArithmeticRanges config={config} onChange={editConfig}/><p className="hint">Subtraction stays nonnegative. Multiplication uses a separate range for each factor. Division always gives a whole-number answer.</p>{error&&<p className="danger" role="alert">{error}</p>}<button className="primary full" onClick={start}>Start sprint <span>↗</span></button></section><aside><section className="panel"><p className="eyebrow">THE RULES</p><h2>Speed, with accuracy.</h2><p className="muted">Type the answer and move straight to the next problem. Every correct answer earns one point.</p><div className="rule"><kbd>enter</kbd><span>Check an answer</span></div><div className="rule"><kbd>esc</kbd><span>Skip a problem</span></div><p className="hint">Incorrect checks and skips lower accuracy. The timer continues if you switch tabs.</p></section><section className="panel presets"><h2>Saved presets</h2>{presets.length>0?<select aria-label="Load preset" value="" onChange={e=>{const p=presets.find(x=>x.id===e.target.value);if(p)editConfig(editableArithmeticConfig(p.config));}}><option value="">Choose a preset</option>{presets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>:<p className="muted">Your preferred settings, one click away.</p>}<form onSubmit={async e=>{e.preventDefault();if(!validConfig(config)){setError('Fix the session settings before saving.');return;}try{await onPreset({id:crypto.randomUUID(),game:'arithmetic',name:name.trim(),config:structuredClone(config)});setName('');setError('');}catch(e){setError((e as Error).message);}}}><input aria-label="Preset name" placeholder="Preset name" maxLength={60} required value={name} onChange={e=>setName(e.target.value)}/><button disabled={!name.trim()}>Save</button></form></section></aside></div></main>;
}
