import {useEffect,useRef,useState} from 'react';
import {createTradingRound,quoteTradingRound,settleTradingRound,tradingDefaults,tradingQuoteError,validTradingConfig} from '../../shared/trading.mjs';
import type {Difficulty,PassiveLeg,Preset,Session,TradingConfig,TradingRecord,TradingRound} from '../lib/types';
type Props={presets:Preset<TradingConfig>[];onSave:(s:Session)=>Promise<void>;onPreset:(p:Preset<TradingConfig>)=>Promise<void>;onBusy:(v:boolean)=>void};
type Phase='setup'|'quote'|'passive-review'|'take'|'review'|'result';
const signed=(v:number)=>`${v>=0?'+':''}${v.toFixed(2)}`;
const fields:{key:keyof TradingConfig;label:string;min:number;max:number;step?:number}[]=[
 {key:'rounds',label:'Rounds',min:3,max:50},{key:'quoteSeconds',label:'Seconds to quote',min:5,max:120},{key:'takeSeconds',label:'Seconds to take',min:5,max:120},
 {key:'maxValue',label:'Maximum fair value (minimum is 20)',min:20,max:1000},{key:'maxSpread',label:'Maximum quoting spread',min:0.1,max:10,step:0.1},
 {key:'aggressiveness',label:'Counterparty aggressiveness',min:0,max:1,step:0.05},{key:'noise',label:'Counterparty valuation noise (±)',min:0,max:20,step:0.5},
 {key:'noiseTradeProbability',label:'Random trade probability',min:0,max:1,step:0.05},{key:'bookSpread',label:'Separate book spread',min:0.1,max:10,step:0.1},
 {key:'bookSkew',label:'Separate book midpoint skew (±)',min:0,max:10,step:0.1},{key:'settlementRisk',label:'Settlement shock (± whole units)',min:0,max:15}
];
export default function TradingGame({presets,onSave,onPreset,onBusy}:Props){
 const [config,setConfig]=useState<TradingConfig>(structuredClone(tradingDefaults.Easy)),[difficulty,setDifficulty]=useState<Difficulty>('Easy');
 const [phase,setPhase]=useState<Phase>('setup'),[round,setRound]=useState<TradingRound|null>(null),[passive,setPassive]=useState<PassiveLeg|null>(null),[records,setRecords]=useState<TradingRecord[]>([]);
 const [bid,setBid]=useState(''),[ask,setAsk]=useState(''),[remaining,setRemaining]=useState(0),[error,setError]=useState('');
 const [result,setResult]=useState<Session|null>(null),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false);
 const [presetName,setPresetName]=useState(''),[presetSaving,setPresetSaving]=useState(false);
 const bidInput=useRef<HTMLInputElement>(null),askInput=useRef<HTMLInputElement>(null),continueButton=useRef<HTMLButtonElement>(null),buyButton=useRef<HTMLButtonElement>(null);
 const current=useRef<TradingRound|null>(null),passiveRef=useRef<PassiveLeg|null>(null),recordRef=useRef<TradingRecord[]>([]),stage=useRef<Phase>('setup');
 const clock=useRef({session:0,start:0,deadline:0,quoteMs:0});const timeoutRef=useRef<()=>void>(()=>{}),actionRef=useRef<(a:'buy'|'sell'|'pass')=>void>(()=>{});
 function move(p:Phase){stage.current=p;setPhase(p);}
 useEffect(()=>()=>{stage.current='setup';onBusy(false);},[onBusy]);
 useEffect(()=>{if(phase==='quote')bidInput.current?.focus();if(phase==='take')buyButton.current?.focus();if(phase==='review'||phase==='passive-review')continueButton.current?.focus();},[phase]);
 useEffect(()=>{if(phase!=='quote'&&phase!=='take')return;const timer=setInterval(()=>{const left=Math.max(0,Math.ceil((clock.current.deadline-performance.now())/1000));setRemaining(left);if(!left)timeoutRef.current();},100);return()=>clearInterval(timer);},[phase]);
 useEffect(()=>{if(phase!=='take')return;const key=(e:KeyboardEvent)=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey)return;const a=({b:'buy',s:'sell',p:'pass'} as const)[e.key.toLowerCase() as 'b'|'s'|'p'];if(a){e.preventDefault();actionRef.current(a);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[phase]);
 useEffect(()=>{if(['setup','result'].includes(phase)||(result&&saved))return;const prevent=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[phase,result,saved]);
 function timer(seconds:number){clock.current.start=performance.now();clock.current.deadline=clock.current.start+seconds*1000;setRemaining(seconds);}
 function beginRound(){const r=createTradingRound(config);current.current=r;setRound(r);passiveRef.current=null;setPassive(null);setBid('');setAsk('');setError('');timer(config.quoteSeconds);move('quote');}
 function start(){if(!validTradingConfig(config)){setError('Keep settings within the displayed limits.');return;}recordRef.current=[];setRecords([]);setResult(null);setSaved(false);clock.current.session=performance.now();onBusy(true);beginRound();}
 async function persist(s:Session){setSaving(true);setError('');try{await onSave(s);setSaved(true);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 function submitQuote(timeout=false){
  if(stage.current!=='quote'||!current.current)return;
  const now=performance.now();timeout=timeout||now>=clock.current.deadline;
  const quote=timeout?null:{bid:bid.trim()?Number(bid):NaN,ask:ask.trim()?Number(ask):NaN};
  if(quote){const message=tradingQuoteError(config,quote.bid,quote.ask);if(message){setError(message);return;}}
  const fill=quoteTradingRound(current.current,quote,config);passiveRef.current=fill;setPassive(fill);clock.current.quoteMs=Math.min(now-clock.current.start,config.quoteSeconds*1000);setError('');move('passive-review');
 }
 function beginTaking(){if(stage.current!=='passive-review')return;timer(config.takeSeconds);move('take');}
 function complete(all:TradingRecord[]){
  const sum=(f:(r:TradingRecord)=>number)=>all.reduce((n,r)=>n+f(r),0);
  const passivePnl=sum(r=>r.passivePnl),activePnl=sum(r=>r.activePnl),pnl=passivePnl+activePnl;
  const quoteTimeouts=sum(r=>Number(r.passive.timedOut)),activeTimeouts=sum(r=>Number(r.activeTimedOut));
  const passiveFills=sum(r=>Number(r.passive.inventoryDelta!==0)),activeFills=sum(r=>Number(r.action!=='pass')),fills=passiveFills+activeFills;
  const correct=sum(r=>Number(r.correct)),responses=2*all.length-quoteTimeouts-activeTimeouts;
  const s:Session={id:crypto.randomUUID(),timestamp:new Date().toISOString(),game:'trading',difficulty,config:structuredClone(config),score:pnl,pnl,passivePnl,activePnl,grossPnl:sum(r=>r.grossPnl),penalties:quoteTimeouts+activeTimeouts,
   rounds:all.length,correct,errors:all.length-correct,accuracy:correct/all.length,quoteTimeouts,activeTimeouts,passiveFills,activeFills,fills,fillRate:fills/(2*all.length),
   avgResponseMs:responses?sum(r=>(r.passive.timedOut?0:r.quoteMs)+(r.activeTimedOut?0:r.takeMs))/responses:0,duration:Math.max(0.001,(performance.now()-clock.current.session)/1000)};
  setResult(s);
 }
 function take(action:'buy'|'sell'|'pass',timeout=false){
  if(stage.current!=='take'||!current.current||!passiveRef.current)return;
  const now=performance.now();timeout=timeout||now>=clock.current.deadline;
  const outcome=settleTradingRound(current.current,passiveRef.current,action,timeout);
  const r:TradingRecord={...outcome,round:current.current,passive:passiveRef.current,quoteMs:clock.current.quoteMs,takeMs:Math.min(now-clock.current.start,config.takeSeconds*1000)};
  const all=[...recordRef.current,r];recordRef.current=all;setRecords(all);move('review');if(all.length===config.rounds)complete(all);
 }
 actionRef.current=take;timeoutRef.current=()=>{if(stage.current==='quote')submitQuote(true);else if(stage.current==='take')take('pass',true);};
 function next(){if(stage.current!=='review')return;if(recordRef.current.length===config.rounds){move('result');onBusy(false);if(result)void persist(result);}else beginRound();}
 function edit(c:TradingConfig){setConfig(c);setDifficulty('Custom');}
 const total=records.reduce((n,r)=>n+r.pnl,0),passiveTotal=records.reduce((n,r)=>n+r.passivePnl,0),activeTotal=records.reduce((n,r)=>n+r.activePnl,0);
 const fillText=(p:PassiveLeg)=>p.timedOut?'Quote timed out · charge 1.00':p.action==='pass'?'Counterparty passed · no fill':`You ${p.action==='buy'?'sold':'bought'} 1 @ ${p.price!.toFixed(2)}`;
 if(phase==='result'&&result)return <main className="result dice-result"><p className="eyebrow">SESSION COMPLETE · COMBINED TRADING</p><h1>Both sides of the market.</h1><div className={`bigscore ${result.score<0?'danger':''}`}>{signed(result.score)}<span>combined net P&L</span></div>
  <div className="metrics"><Metric value={signed(result.passivePnl!)} label="Passive net P&L"/><Metric value={signed(result.activePnl!)} label="Active net P&L"/><Metric value={`${Math.round(result.accuracy*100)}%`} label="Optimal taking decisions"/><Metric value={`${result.passiveFills} / ${result.activeFills}`} label="Passive / active fills"/></div>
  <section className="panel"><h2>Your result</h2><p>Gross P&L {signed(result.grossPnl!)} − {result.penalties!.toFixed(2)} timeout charges = {signed(result.pnl!)}.</p><p className="hint">{result.quoteTimeouts} quote timeouts · {result.activeTimeouts} taking timeouts. Each side’s net P&L includes its own charges. Payout risk can make positive-edge trades lose money in a short session.</p></section>
  <p className="muted">{saving?'Saving session…':saved?'Session saved.':'Session not yet saved.'}</p>{error&&<p className="danger" role="alert">{error} <button disabled={saving} onClick={()=>persist(result)}>Retry save</button></p>}
  <button className="primary" disabled={!saved} onClick={start}>Trade again ↗</button> <button disabled={!saved} onClick={()=>move('setup')}>Adjust settings</button><p><a href="#/history">View trading history →</a></p>
  <details className="panel trade-details"><summary>Review all {records.length} rounds</summary><div className="tablewrap"><table><thead><tr><th>Round</th><th>Fair / payout</th><th>Your quote</th><th>Passive fill</th><th>Book</th><th>Taking</th><th>Passive P&L</th><th>Active P&L</th></tr></thead><tbody>{records.map((r,i)=><tr key={i}><td>{i+1}</td><td>{r.round.fairValue.toFixed(2)} / {r.round.payout.toFixed(2)}</td><td>{r.passive.timedOut?'Timed out':`${r.passive.bid!.toFixed(2)} / ${r.passive.ask!.toFixed(2)}`}</td><td>{fillText(r.passive)}</td><td>{r.round.bid.toFixed(2)} / {r.round.ask.toFixed(2)}</td><td>{r.activeTimedOut?'Timed out':r.action}</td><td>{signed(r.passivePnl)}</td><td>{signed(r.activePnl)}</td></tr>)}</tbody></table></div></details>
 </main>;
 if(round&&['quote','passive-review','take','review'].includes(phase)){
  const review=phase==='review'?records.at(-1):undefined;const timed=phase==='quote'||phase==='take';
  return <main className="play dice-play"><div className="playbar"><span>COMBINED TRADING</span><span>Round {review?records.length:records.length+1} / {config.rounds}</span><span className={timed&&remaining<=5?'danger':''}>{timed?`${remaining}s`:'Review'}<small>{timed?(phase==='quote'?'to quote':'to take'):'timer paused'}</small></span></div>
   <div className="market-metrics"><Metric value={signed(total)} label="Settled net P&L"/><Metric value={signed(passiveTotal)} label="Passive"/><Metric value={signed(activeTotal)} label="Active"/></div>
   <section className="event-surface trading-surface"><p className="eyebrow">{phase==='quote'?'01 / MAKE A MARKET':phase==='passive-review'?'01 / YOUR FILL':phase==='take'?'02 / TAKE THE BOOK':'ROUND SETTLED'}</p><h1>Fair value {round.fairValue.toFixed(2)}</h1><p className="hint">One contract · payout = fair value ± up to {config.settlementRisk} · symmetric whole-unit shock</p>
    {phase==='quote'&&<form onSubmit={e=>{e.preventDefault();submitQuote();}}><div className="quote-inputs"><label>Your bid<input ref={bidInput} aria-label="Your bid" type="number" min="0" max={config.maxValue+30} step="0.01" value={bid} onChange={e=>setBid(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();askInput.current?.focus();}}}/><small>You buy here</small></label><span>/</span><label>Your ask<input ref={askInput} aria-label="Your ask" type="number" min="0" max={config.maxValue+30} step="0.01" value={ask} onChange={e=>setAsk(e.target.value)}/><small>You sell here</small></label></div><p className="hint">Spread ≤ {config.maxSpread}. The counterparty can buy, sell or pass for one unit.</p>{error&&<p className="danger" role="alert">{error}</p>}<button className="primary">Post quote ↵</button></form>}
    {phase==='passive-review'&&passive&&<div className="panel" role="status"><h2>{fillText(passive)}</h2><p>Position: {passive.inventoryDelta>0?'+':''}{passive.inventoryDelta} units · cash: {signed(passive.cashDelta)}</p><p>Expected edge: {signed(passive.edge)} before charges.</p><p className="hint">The separate book appears next. Its quote was generated independently of your quote and fill. Both trades share this round’s payout; it has not been revealed.</p><button ref={continueButton} className="primary" onClick={beginTaking}>Open taking stage ↵</button></div>}
    {phase==='take'&&passive&&<><p className="hint">{fillText(passive)} · current position {passive.inventoryDelta}</p><div className="trading-book"><div><small>BOOK BID · YOU SELL</small><strong>{round.bid.toFixed(2)}</strong></div><span>/</span><div><small>BOOK ASK · YOU BUY</small><strong>{round.ask.toFixed(2)}</strong></div></div><div className="trading-actions"><button ref={buyButton} className="primary" onClick={()=>take('buy')}>Buy 1 <kbd>B</kbd></button><button onClick={()=>take('sell')}>Sell 1 <kbd>S</kbd></button><button onClick={()=>take('pass')}>Pass <kbd>P</kbd></button></div><p className="hint">Firm quotes, one unit. Buy below fair value; sell above fair value. Pass if neither offers positive edge.</p></>}
    {review&&<div className="panel" role="status"><h2>Payout {round.payout.toFixed(2)} · net P&L {signed(review.pnl)}</h2><div className="score-breakdown"><span>Passive <b>{signed(review.passivePnl)}</b></span><span>Active <b>{signed(review.activePnl)}</b></span><span>Charges <b>{review.penalties.toFixed(2)}</b></span></div><p>{fillText(review.passive)}. Taking: {review.activeTimedOut?'timed out':review.action}{review.price!==null?` @ ${review.price.toFixed(2)}`:''}.</p><p>Taking edge: {signed(review.activeEdge)} · best decision: {review.bestAction} ({signed(review.bestEdge)}).</p><p className="hint">Net position before settlement: {review.inventory}. Both trades settled at {round.payout.toFixed(2)}; inventory is now zero. A timeout costs 1.00 per stage.</p><button ref={continueButton} className="primary" onClick={next}>{records.length===config.rounds?'See results':'Next round'} ↵</button></div>}
   </section>
  </main>;
 }
 function field(item:typeof fields[number]){return <label className="mental-setting" key={item.key}><span>{item.label}<small>{item.min}–{item.max}</small></span><input aria-label={item.label} type="number" min={item.min} max={item.max} step={item.step||1} value={config[item.key]} onChange={e=>edit({...config,[item.key]:Number(e.target.value)})}/></label>;}
 return <main><div className="pageheading"><div><p className="eyebrow">07 / MARKETS</p><h1>Combined trading</h1><p className="muted">Quote with discipline. Take when there is edge.</p></div><a className="textlink" href="#/">← All modes</a></div><div className="setupgrid"><section className="panel"><h2>Your session</h2><label className="fieldlabel">Difficulty</label><div className="segmented">{(['Easy','Medium','Hard','Custom'] as Difficulty[]).map(d=><button key={d} aria-pressed={difficulty===d} className={difficulty===d?'selected':''} onClick={()=>{setDifficulty(d);if(d!=='Custom')setConfig(structuredClone(tradingDefaults[d]));}}>{d}</button>)}</div>{fields.slice(0,5).map(field)}<details className="advanced"><summary>Counterparty, book & settlement</summary>{fields.slice(5).map(field)}</details>{error&&<p className="danger" role="alert">{error}</p>}<button className="primary full" onClick={start}>Start trading <span>↗</span></button></section>
  <aside><section className="panel"><p className="eyebrow">THE RULES</p><h2>Make. Take. Settle.</h2><p className="muted">First quote around a displayed fair value. A simulated counterparty may trade against you. Review the fill, then choose buy, sell or pass against a separate firm book.</p><p className="hint">Both one-unit trades settle at the same payout. Their P&L adds together, less 1.00 for each timed-out stage. Positions reset after each round. Setting settlement shock to zero makes payout equal fair value.</p><p className="hint">The counterparty knows fair value, with configurable noise, but never the payout. The separate book is generated independently of your quote. Positive expected edge does not guarantee a profitable draw.</p><div className="rule"><kbd>enter</kbd><span>Bid → ask → submit; advance reviews</span></div><div className="rule"><kbd>B / S / P</kbd><span>Buy / sell / pass in the taking stage</span></div></section>
  <section className="panel presets"><h2>Saved presets</h2>{presets.length?<select aria-label="Load preset" value="" onChange={e=>{const p=presets.find(p=>p.id===e.target.value);if(p)edit(structuredClone(p.config));}}><option value="">Choose a preset</option>{presets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>:<p className="muted">Save a pace, trader profile and book.</p>}<form onSubmit={async e=>{e.preventDefault();if(!validTradingConfig(config)){setError('Fix the settings before saving.');return;}setPresetSaving(true);try{await onPreset({id:crypto.randomUUID(),game:'trading',name:presetName.trim(),config:structuredClone(config)});setPresetName('');setError('');}catch(e){setError((e as Error).message);}finally{setPresetSaving(false);}}}><input aria-label="Preset name" placeholder="Preset name" maxLength={60} required value={presetName} onChange={e=>setPresetName(e.target.value)}/><button disabled={!presetName.trim()||presetSaving}>Save</button></form></section></aside></div></main>;
}
function Metric({value,label}:{value:string|number;label:string}){return <div className="stat"><strong>{value}</strong><span>{label}</span></div>;}
